/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResearchersIndexRouteImport } from './routes/researchers.index'
import { Route as ResearchersSlugRouteImport } from './routes/researchers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchersIndexRoute = ResearchersIndexRouteImport.update({
  id: '/researchers/',
  path: '/researchers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchersSlugRoute = ResearchersSlugRouteImport.update({
  id: '/researchers/$slug',
  path: '/researchers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/researchers/$slug': typeof ResearchersSlugRoute
  '/researchers/': typeof ResearchersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/researchers/$slug': typeof ResearchersSlugRoute
  '/researchers': typeof ResearchersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/researchers/$slug': typeof ResearchersSlugRoute
  '/researchers/': typeof ResearchersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/services' | '/researchers/$slug' | '/researchers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/services' | '/researchers/$slug' | '/researchers'
  id: '__root__' | '/' | '/services' | '/researchers/$slug' | '/researchers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRoute: typeof ServicesRoute
  ResearchersSlugRoute: typeof ResearchersSlugRoute
  ResearchersIndexRoute: typeof ResearchersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researchers/': {
      id: '/researchers/'
      path: '/researchers'
      fullPath: '/researchers/'
      preLoaderRoute: typeof ResearchersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researchers/$slug': {
      id: '/researchers/$slug'
      path: '/researchers/$slug'
      fullPath: '/researchers/$slug'
      preLoaderRoute: typeof ResearchersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRoute: ServicesRoute,
  ResearchersSlugRoute: ResearchersSlugRoute,
  ResearchersIndexRoute: ResearchersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
